service: monitor-puppeteer
frameworkVersion: ">=1.34.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-apigw-binary
  - serverless-apigwy-binary

custom:
  apigwBinary:
    types:
      - "*/*"

package:
  exclude:
    - chrome-aws-lambda/**
    - node_modules/puppeteer/.local-chromium/**

functions:
  puppeteer-orchestrator:
    handler: handler.index
    timeout: 30
    memorySize: 2048
    events:
      - http:
          method: GET
          path: /screenshot
          contentHandling: CONVERT_TO_BINARY
    layers:
      - { Ref: ChromeLambdaLayer }

layers:
  chrome:
    path: layer
