service: monitor-puppeteer
frameworkVersion: ">=1.34.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x

package:
  exclude:
    - layer/**
    - chrome-aws-lambda/**
    - node_modules/chrome-aws-lambda/**

layers:
  chrome:
    package:
      artifact: layer/chrome.zip
